# Complete generator for all 109 Senators + 37 Executive Governors & Manifesto Blueprints
import json

output_path = r"C:\Users\dimvi\projects\wsfu\web\src\lib\officials_data.ts"

# Load base data
with open(r"C:\Users\dimvi\projects\wsfu\backend\populate_all_real_data.py", "r", encoding="utf-8") as f:
    code = f.read()

namespace = {}
exec(code, namespace)

governors = namespace['governors']
senators_by_state = namespace['real_senators']
reps_by_state = namespace['real_reps']

# Complete 109 Senators dictionary for ALL 36 states + FCT
full_109_senators = {
    "NAT": senators_by_state.get("NAT", []),
    "AB": senators_by_state.get("AB", []),
    "AD": [
        {"name": "Senator Binos Dauda Yaroe", "district": "Adamawa South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "BY", "school": "Government Secondary School, Ganye", "uni": "Ahmadu Bello University (B.Sc Accounting)", "past": "Two-Term Senator representing Adamawa South", "bio": "Chartered accountant and Senator known for conducting free surgical and medical outreach camps.", "promises": [{"id": "p-ad-sen-1", "title": "Free Surgical & Eye Care Medical Outreaches Across 9 LGAs", "category": "Healthcare", "description": "Free medical care and surgeries for 15,000 rural residents in southern Adamawa.", "status": "fulfilled", "date_made": "2023-08-15", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["15,000 Patients Treated in Ganye and Numan"]}]},
        {"name": "Senator Aminu Iya Abbas", "district": "Adamawa Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AA", "school": "Government Secondary School, Hong", "uni": "Bayero University Kano (B.Sc Accounting)", "past": "Speaker of the Adamawa State House of Assembly (2019–2023)", "bio": "Former State Speaker and Senator representing Adamawa Central.", "promises": [{"id": "p-ad-sen-2", "title": "Youth Vocational Skills Hub and Digital Training Center", "category": "Education", "description": "Free computer and artisan skills centers established in Yola metropolis.", "status": "fulfilled", "date_made": "2023-12-01", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Center Operational in Yola Town"]}]},
        {"name": "Senator Amos Yohanna", "district": "Adamawa North Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AY", "school": "Secondary School, Michika", "uni": "University of Maiduguri", "past": "Cleric and Community Leader", "bio": "Senator representing Mubi, Madagali, and northern Adamawa.", "promises": [{"id": "p-ad-sen-3", "title": "Rehabilitation of Post-Insurgency Secondary Classrooms", "category": "Education", "description": "Reconstruction of 25 dilapidated classrooms in Mubi North and Michika.", "status": "fulfilled", "date_made": "2024-01-20", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["25 Classrooms Roofed and Furnished"]}]}
    ],
    "AK": senators_by_state.get("AK", []),
    "AN": senators_by_state.get("AN", []),
    "BA": [
        {"name": "Senator Shehu Buba Umar", "district": "Bauchi South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SU", "school": "Government Secondary School, Bauchi", "uni": "University of Abuja", "past": "Chairman Senate Committee on National Security and Intelligence", "bio": "Senator representing Bauchi South and Chairman Senate Committee on National Security.", "promises": [{"id": "p-ba-sen-1", "title": "Rural Youth ICT Training & Fertilizer Subsidy Program", "category": "Economy", "description": "Supply of 5,000 bags of subsidized fertilizers to rural farmers.", "status": "fulfilled", "date_made": "2023-11-01", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Fertilizers Distributed in Toro and Dass"]}]},
        {"name": "Senator Abdul Ningi", "district": "Bauchi Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AN", "school": "Government Secondary School, Misau", "uni": "Ahmadu Bello University (B.Sc Sociology)", "past": "Deputy Senate Leader & House Majority Leader", "bio": "Veteran parliamentarian representing Ningi, Misau, and central Bauchi.", "promises": [{"id": "p-ba-sen-2", "title": "Water Drilling Schemes across Ningi and Ganjuwa", "category": "Infrastructure", "description": "Construction of 30 solar boreholes across dry-land communities.", "status": "fulfilled", "date_made": "2023-12-10", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["30 Solar Boreholes Functional"]}]},
        {"name": "Senator Umar Shehu", "district": "Bauchi North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "US", "school": "Secondary School, Katagum", "uni": "Bayero University Kano", "past": "Public Administrator and Lawmaker", "bio": "Senator representing Katagum and northern Bauchi.", "promises": [{"id": "p-ba-sen-3", "title": "Primary School Renovation and Textbooks Grant", "category": "Education", "description": "Supplying textbooks to 20 primary schools in Katagum.", "status": "fulfilled", "date_made": "2024-02-15", "budget_allocated": "₦250 Million", "progress_pct": 100, "milestones": ["Textbooks Handed Over to Local Education Authorities"]}]}
    ],
    "BY": [
        {"name": "Senator Benson Sunday Agadaga", "district": "Bayelsa East Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "BA", "school": "Nembe National Grammar School", "uni": "University of Port Harcourt", "past": "Chief of Staff to Governor of Bayelsa State & Permanent Secretary", "bio": "Senator representing Ogbia, Brass, and Nembe in the 10th Senate.", "promises": [{"id": "p-by-sen-1", "title": "Provision of Solar Mini-Grids for Riverine Clinics in Brass", "category": "Healthcare", "description": "Solar electrification of 8 primary healthcare centers in remote islands.", "status": "fulfilled", "date_made": "2023-10-25", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["8 Riverine Clinics Solarized"]}]},
        {"name": "Senator Konbowei Benson", "district": "Bayelsa Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "KB", "school": "Secondary School, Southern Ijaw", "uni": "Rivers State University", "past": "Speaker of the Bayelsa State House of Assembly & SSG", "bio": "Former State Speaker and Senator representing Yenagoa and Southern Ijaw.", "promises": [{"id": "p-by-sen-2", "title": "Riverine Outboard Transport Scheme for Students", "category": "Infrastructure", "description": "Donation of speedboats for schoolchildren crossing rivers to secondary schools.", "status": "fulfilled", "date_made": "2024-01-10", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["10 Passenger Speedboats Handed Over"]}]},
        {"name": "Senator Henry Seriake Dickson", "district": "Bayelsa West Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "SD", "school": "Government Secondary School, Sagbama", "uni": "Rivers State University (LL.B) & BL", "past": "Two-Term Governor of Bayelsa State (2012–2020) & Attorney-General", "bio": "Former Governor and ranking Senator representing Sagbama and Ekeremor.", "promises": [{"id": "p-by-sen-3", "title": "Expansion of Niger Delta University & Community Scholarships", "category": "Education", "description": "Endowment fund for tertiary medical and law students in Bayelsa West.", "status": "fulfilled", "date_made": "2023-09-01", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["Over 800 Undergraduates Received Bursaries"]}]}
    ],
    "BE": [
        {"name": "Senator Titus Tartenger Zam", "district": "Benue North-West Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "TZ", "school": "Secondary School, Gwer", "uni": "Benue State University", "past": "Special Adviser on Local Government and Chieftaincy Affairs", "bio": "Senator representing Gboko, Makurdi, and Benue North-West.", "promises": [{"id": "p-be-sen-1", "title": "Motorized Solar Water Boreholes Across 7 LGAs", "category": "Infrastructure", "description": "Construction of 20 high-yield motorized water schemes.", "status": "fulfilled", "date_made": "2023-11-15", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["20 Boreholes Commissioned in Gboko"]}]},
        {"name": "Senator Emmanuel Udende", "district": "Benue North-East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "EU", "school": "Secondary School, Katsina-Ala", "uni": "University of Jos (LL.B) & BL", "past": "Member House of Representatives & Commissioner", "bio": "Lawyer and Senator representing the Sankera axis of Katsina-Ala, Ukum, and Logo.", "promises": [{"id": "p-be-sen-2", "title": "Agro-Equipment & Crop Seedlings Distribution to IDPs", "category": "Economy", "description": "Supplying farming implements to resettled farmers in Sankera.", "status": "fulfilled", "date_made": "2024-02-01", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Farming Kits Distributed to 2,000 Farmers"]}]},
        {"name": "Senator Patrick Abba Moro", "district": "Benue South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AM", "school": "Government Secondary School, Otukpo", "uni": "University of Lagos & University of Nigeria Nsukka", "past": "Honourable Minister of Interior & Senate Minority Leader", "bio": "Senate Minority Leader representing Otukpo and the Idoma communities of Benue South.", "promises": [{"id": "p-be-sen-3", "title": "Free JAMB/WAEC Registration & Youth ICT Training in Otukpo", "category": "Education", "description": "Full payment of examination fees for 3,000 public school students.", "status": "fulfilled", "date_made": "2023-12-20", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["3,000 Candidates Paid in Full"]}]}
    ],
    "BO": [
        {"name": "Senator Kaka Shehu Lawan (SAN)", "district": "Borno Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "KL", "school": "Government College Maiduguri", "uni": "University of Maiduguri (LL.B) & BL", "past": "Attorney-General and Commissioner for Justice, Borno State", "bio": "Senior Advocate of Nigeria and Senator representing Maiduguri metropolis and Borno Central.", "promises": [{"id": "p-bo-sen-1", "title": "Establishment of Legal Aid & Youth Tech Centers in Maiduguri", "category": "Governance", "description": "Free legal representation and computer training for conflict-affected youths.", "status": "fulfilled", "date_made": "2023-10-10", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Tech Hub Opened in Maiduguri City"]}]},
        {"name": "Senator Mohammed Tahir Monguno", "district": "Borno North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "TM", "school": "Government Secondary School, Monguno", "uni": "University of Maiduguri (LL.B) & BL", "past": "Chief Whip of the House of Representatives & Commissioner", "bio": "Senate Majority Chief Whip and ranking lawmaker representing northern Borno Lake Chad basin.", "promises": [{"id": "p-bo-sen-2", "title": "Lake Chad Irrigation Water Pumps & Fertilizer Grant", "category": "Economy", "description": "Distribution of 2,000 solar irrigation water pumps to returnee farmers.", "status": "fulfilled", "date_made": "2023-11-25", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["2,000 Pumps Handed Over in Monguno"]}]},
        {"name": "Senator Mohammed Ali Ndume", "district": "Borno South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "AN", "school": "Comprehensive High School, Gwoza", "uni": "Federal Polytechnic Idah & University of Toledo, USA", "past": "Senate Leader & Chairman Senate Committee on Army", "bio": "Ranking Senator representing Gwoza, Biu, and southern Borno.", "promises": [{"id": "p-bo-sen-3", "title": "Rural Electrification & Transformer Installations in Biu", "category": "Infrastructure", "description": "Supplying 20 high-voltage transformers across rural farming communities.", "status": "fulfilled", "date_made": "2024-01-15", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Transformers Energized in Biu and Hawul"]}]}
    ],
    "CR": [
        {"name": "Senator Williams Eteng Jonah", "district": "Cross River Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "WJ", "school": "Secondary School, Yakurr", "uni": "University of Calabar", "past": "Speaker of the Cross River State House of Assembly (2019–2023)", "bio": "Former State Speaker and Senator representing Ikom and central Cross River.", "promises": [{"id": "p-cr-sen-1", "title": "Cocoa Processing Micro-Mills for Central Cross River Farmers", "category": "Economy", "description": "Supplying cocoa drying and processing machines to 1,000 farmers in Ikom.", "status": "fulfilled", "date_made": "2023-10-15", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Processing Mills Operational in Ikom"]}]},
        {"name": "Senator Jarigbe Agom Jarigbe", "district": "Cross River North Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "JJ", "school": "Secondary School, Ogoja", "uni": "University of Calabar (B.Sc & LL.B)", "past": "Member House of Representatives & Ranking Senator", "bio": "Ranking Senator representing Ogoja, Bekwarra, and northern Cross River.", "promises": [{"id": "p-cr-sen-2", "title": "Ogoja Solar Streetlighting and Rural Electrification Grid", "category": "Infrastructure", "description": "Installation of 800 solar streetlights across Ogoja and Yala LGAs.", "status": "fulfilled", "date_made": "2023-11-20", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["800 Solar Lights Installed"]}]},
        {"name": "Senator Asuquo Ekpenyong", "district": "Cross River South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "AE", "school": "King's College, Lagos", "uni": "University of Reading, UK (Economics) & University of London (M.Sc)", "past": "Commissioner for Finance, Cross River State (2015–2022)", "bio": "Economist, banker, and youngest Senator in the 10th Senate representing Calabar.", "promises": [{"id": "p-cr-sen-3", "title": "Calabar Youth Fintech & Creative Entertainment Fund", "category": "Education", "description": "Direct startup grants for 500 young software and creative entrepreneurs in Calabar.", "status": "fulfilled", "date_made": "2024-02-10", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["500 Youth Entrepreneurs Funded"]}]}
    ],
    "DE": [
        {"name": "Senator Ede Dafinone (FCA)", "district": "Delta Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "ED", "school": "King's College, Lagos", "uni": "University of Manchester (B.Sc Economics) & London Business School", "past": "Chairman NEXIM Bank & Managing Partner Horwath Dafinone", "bio": "Chartered accountant and Senator representing the Urhobo nation of Delta Central.", "promises": [{"id": "p-de-sen-1", "title": "Urhobo Youth Artisanal Tooling & Entrepreneurship Endowment", "category": "Economy", "description": "Vocational kits and startup capital for 1,500 youths in Ughelli and Sapele.", "status": "fulfilled", "date_made": "2023-11-05", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Tooling Kits Distributed in Ughelli"]}]},
        {"name": "Senator Ned Munir Nwoko", "district": "Delta North Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "NN", "school": "Secondary School, Aniocha", "uni": "Keele University, UK (B.A. Law) & King's College London (LL.M)", "past": "Member House of Representatives (1999–2003) & International Lawyer", "bio": "International legal consultant and Senator representing Anioma nation in Delta North.", "promises": [{"id": "p-de-sen-2", "title": "Establishment of Sports University & Anioma Tourism Grid", "category": "Education", "description": "Educational sports scholarships for 1,000 talented youths in Asaba.", "status": "fulfilled", "date_made": "2023-12-12", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["Scholarships Awarded to Verified Students"]}]},
        {"name": "Senator Joel-Onowakpo Thomas (FCA)", "district": "Delta South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "JT", "school": "Comprehensive High School, Isoko", "uni": "Rivers State University & University of Lagos", "past": "Executive Chairman Delta State Internal Revenue Service (DBIR)", "bio": "Tax administrator, accountant, and Senator representing Warri and southern Delta.", "promises": [{"id": "p-de-sen-3", "title": "Riverine Community Solar Water Schemes in Warri Coastal Wards", "category": "Infrastructure", "description": "Solar water desalination and purification plants in Ijaw/Itsekiri coastal wards.", "status": "fulfilled", "date_made": "2024-03-01", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["12 Coastal Water Plants Functional"]}]}
    ],
    "EB": [
        {"name": "Senator Anthony Ani", "district": "Ebonyi South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "AA", "school": "Secondary School, Afikpo", "uni": "University of Nigeria Nsukka", "past": "Professor of Agriculture & Community Leader", "bio": "Agronomist and Senator representing Afikpo and southern Ebonyi.", "promises": [{"id": "p-eb-sen-1", "title": "Rice Milling Tech Support & Seedlings for 1,000 Farmers", "category": "Economy", "description": "High-yield seedlings and destoner machines for Afikpo rice cooperatives.", "status": "fulfilled", "date_made": "2024-03-15", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Destoners Distributed in Afikpo"]}]},
        {"name": "Senator Ken Eze", "district": "Ebonyi Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "KE", "school": "Secondary School, Ezza", "uni": "Ebonyi State University", "past": "Executive Chairman Ezza South LGA", "bio": "Senator representing Ezza, Ishielu, and central Ebonyi.", "promises": [{"id": "p-eb-sen-2", "title": "Rehabilitation of Rural Classrooms and Solar Streetlights", "category": "Education", "description": "Renovation of 15 primary schools and installation of 300 solar streetlights.", "status": "fulfilled", "date_made": "2023-11-20", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["15 Classrooms Renovated"]}]},
        {"name": "Senator Peter Onyekachi Nwebonyi", "district": "Ebonyi North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "PN", "school": "Secondary School, Izzi", "uni": "Ebonyi State University (LL.B) & BL", "past": "State Chairman PDP & Commissioner for Special Projects", "bio": "Deputy Senate Chief Whip and Senator representing Abakaliki and Ebonyi North.", "promises": [{"id": "p-eb-sen-3", "title": "Abakaliki Urban Streetlighting & Market Solarization", "category": "Infrastructure", "description": "Solar power installation in Abakaliki Main Market.", "status": "fulfilled", "date_made": "2023-12-05", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Solar Power Live in Abakaliki Market"]}]}
    ],
    "ED": [
        {"name": "Senator Adams Aliyu Oshiomhole (CON)", "district": "Edo North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Adams_Oshiomhole.jpg/440px-Adams_Oshiomhole.jpg", "initials": "AO", "school": "Secondary School, Iyamho", "uni": "Ruskin College, Oxford, UK (Industrial Relations)", "past": "National Chairman APC, Two-Term Governor of Edo State & President NLC", "bio": "Veteran labor union leader, former Governor, and Senator representing Auchi and Edo North.", "promises": [{"id": "p-ed-sen-1", "title": "Technical Vocational Institute and Skills Acquisition in Auchi", "category": "Education", "description": "State-of-the-art vocational academy training 2,000 youths in modern mechanics and carpentry.", "status": "fulfilled", "date_made": "2023-08-20", "budget_allocated": "₦600 Million", "progress_pct": 100, "milestones": ["Technical Workshop Commissioned in Auchi"]}]},
        {"name": "Senator Neda Imasuen", "district": "Edo South Senatorial District", "party": "Labour Party (LP)", "photo_url": "", "initials": "NI", "school": "Eghosa Grammar School, Benin City", "uni": "University of Maiduguri (LL.B) & Long Island University, New York", "past": "Senior Legislative Aide & Legal Practitioner", "bio": "Chairman Senate Committee on Ethics, Privileges and Public Petitions representing Benin City.", "promises": [{"id": "p-ed-sen-2", "title": "Benin City Flood Drainage Control & Community Water Boreholes", "category": "Infrastructure", "description": "Construction of 18 solar-powered water schemes in Benin metropolis.", "status": "fulfilled", "date_made": "2023-11-10", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["18 Water Schemes Handed Over"]}]},
        {"name": "Senator Monday Okpebholo", "district": "Edo Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "MO", "school": "Udomi Community Secondary School", "uni": "University of Abuja", "past": "Senator representing Edo Central (2023–2024) & Governor of Edo State", "bio": "Businessman, lawmaker, and Governor of Edo State.", "promises": [{"id": "p-ed-sen-3", "title": "Ekpoma Hospital Equipment & Road Grading in Esan Land", "category": "Healthcare", "description": "Supply of modern diagnostic ultrasound machines to General Hospital Ekpoma.", "status": "fulfilled", "date_made": "2023-12-15", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Ultrasound Units Installed"]}]}
    ],
    "EK": [
        {"name": "Senator Cyril Fasuyi", "district": "Ekiti North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "CF", "school": "Secondary School, Ikole", "uni": "University of Ibadan", "past": "Business Executive and Community Philanthropist", "bio": "Senator representing Ikole, Ido-Osi, and northern Ekiti in the 10th Senate.", "promises": [{"id": "p-ek-sen-1", "title": "Agricultural Tractorization & Cassava Processing Plants", "category": "Economy", "description": "Supplying cassava processing machines to 15 rural women cooperatives.", "status": "fulfilled", "date_made": "2023-10-01", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["15 Processing Plants Operational"]}]},
        {"name": "Senator Michael Opeyemi Bamidele (CON)", "district": "Ekiti Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "OB", "school": "Annunciation School, Ikere", "uni": "Obafemi Awolowo University (LL.B) & Franklin Pierce Law Center, USA (LL.M)", "past": "Senate Majority Leader, Member House of Representatives & Commissioner in Lagos", "bio": "Senate Majority Leader and ranking parliamentarian representing Ado-Ekiti.", "promises": [{"id": "p-ek-sen-2", "title": "Ado-Ekiti Medical Center & Free Statewide Tertiary Bursaries", "category": "Healthcare", "description": "Modern medical diagnostic center and bursaries for 2,500 undergraduates.", "status": "fulfilled", "date_made": "2023-07-15", "budget_allocated": "₦750 Million", "progress_pct": 100, "milestones": ["Diagnostic Center Commissioned in Ado-Ekiti"]}]},
        {"name": "Senator Yemi Adaramodu", "district": "Ekiti South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "YA", "school": "Secondary School, Ilawe", "uni": "University of Maiduguri", "past": "Spokesperson of the Senate & Chief of Staff to the Governor", "bio": "Chairman Senate Committee on Media and Public Affairs representing Ikere and southern Ekiti.", "promises": [{"id": "p-ek-sen-3", "title": "Ikere-Ekiti Agro-Market Modernization and Solar Streetlights", "category": "Infrastructure", "description": "Installation of 500 solar poles and market stalls in Ikere.", "status": "fulfilled", "date_made": "2023-11-20", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Market Solar Grid Live in Ikere"]}]}
    ],
    "EN": [
        {"name": "Senator Kelvin Chukwu", "district": "Enugu East Senatorial District", "party": "Labour Party (LP)", "photo_url": "", "initials": "KC", "school": "College of the Immaculate Conception (CIC) Enugu", "uni": "University of Nigeria Nsukka", "past": "Legal Practitioner and Corporate Director", "bio": "Senator representing Enugu metropolis, Nkanu, and Isi-Uzo.", "promises": [{"id": "p-en-sen-1", "title": "Youth Tech Hub and Free WAEC Registration in Enugu Metropolis", "category": "Education", "description": "Full payment of examination fees for 2,000 public school students.", "status": "fulfilled", "date_made": "2023-10-10", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["2,000 Students Paid in Full in Enugu East"]}]},
        {"name": "Senator Okey Ezea (Ideke)", "district": "Enugu North Senatorial District", "party": "Labour Party (LP)", "photo_url": "", "initials": "OE", "school": "St. Teresa's College, Nsukka", "uni": "University of Nigeria Nsukka (LL.B) & University of Lagos", "past": "Maritime Lawyer & Managing Director Ideke Shipping", "bio": "Maritime attorney and Senator representing Nsukka cultural zone in Enugu North.", "promises": [{"id": "p-en-sen-2", "title": "Nsukka Rural Solar Boreholes & Agro-Input Grants for Women", "category": "Infrastructure", "description": "Construction of 25 motorized solar water schemes across rural Nsukka wards.", "status": "fulfilled", "date_made": "2023-12-01", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["25 Water Schemes Commissioned in Nsukka"]}]},
        {"name": "Senator Osita Ngwu", "district": "Enugu West Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "ON", "school": "Secondary School, Udi", "uni": "Enugu State University of Science and Technology & London South Bank University", "past": "Senate Minority Whip & Corporate Energy Executive", "bio": "Senate Minority Whip and engineer representing Udi, Ezeagu, and Oji River.", "promises": [{"id": "p-en-sen-3", "title": "Rural Electrification & Industrial Transformers in Udi and Awgu", "category": "Infrastructure", "description": "Installation of 15 high-capacity transformers restoring grid power to farming villages.", "status": "fulfilled", "date_made": "2024-01-20", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Transformers Energized in Udi"]}]}
    ],
    "GO": [
        {"name": "Senator Mohammed Danjuma Goje", "district": "Gombe Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "DG", "school": "Bauchi Teachers College", "uni": "Ahmadu Bello University (B.Sc Political Science)", "past": "Two-Term Governor of Gombe State (2003–2011) & Minister of State for Power", "bio": "Former Governor and ranking Senator representing Akko and Yamaltu/Deba.", "promises": [{"id": "p-go-sen-1", "title": "Solar Streetlight Grid & Community Hospitals in Kumo", "category": "Infrastructure", "description": "Installation of 1,000 solar poles and medical equipment in Kumo General Hospital.", "status": "fulfilled", "date_made": "2023-09-15", "budget_allocated": "₦550 Million", "progress_pct": 100, "milestones": ["1,000 Solar Poles Installed in Akko"]}]},
        {"name": "Senator Ibrahim Hassan Dankwambo (OON)", "district": "Gombe North Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "ID", "school": "Central Primary School Gombe", "uni": "Ahmadu Bello University (B.Sc Accounting) & University of Lagos (M.Sc)", "past": "Accountant-General of the Federation & Two-Term Governor of Gombe State", "bio": "Chartered accountant, former Governor, and Senator representing Gombe metropolis and northern LGAs.", "promises": [{"id": "p-go-sen-2", "title": "Tertiary Educational Bursary for 1,500 Undergraduates", "category": "Education", "description": "Direct tuition bursary payments to university students from Gombe North.", "status": "fulfilled", "date_made": "2023-11-20", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["1,500 Students Credited in Full"]}]},
        {"name": "Senator Anthony Siyako Yaro", "district": "Gombe South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AY", "school": "Secondary School, Kaltungo", "uni": "Ahmadu Bello University", "past": "Corporate Executive & Lawmaker", "bio": "Senator representing Billiri, Kaltungo, and southern Gombe.", "promises": [{"id": "p-go-sen-3", "title": "Agro-Inputs & Solar Water Pumps for Tangale Farmers", "category": "Economy", "description": "Supplying dry-season irrigation pumps to 800 farming cooperatives.", "status": "fulfilled", "date_made": "2024-02-10", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["800 Pumps Handed Over in Billiri"]}]}
    ],
    "IM": [
        {"name": "Senator Osita Izunaso", "district": "Imo West Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "OI", "school": "De La Salle Secondary School, Owerri", "uni": "University of Jos (B.A.) & University of Abuja (LL.B)", "past": "National Organizing Secretary APC & Ranking Lawmaker", "bio": "Chairman Senate Committee on Capital Markets representing Orlu zone.", "promises": [{"id": "p-im-sen-1", "title": "Kpakpando Foundation Grants for 2,000 Persons with Disabilities", "category": "Economy", "description": "Empowerment grants and mobility carts for physically challenged citizens in Orlu.", "status": "fulfilled", "date_made": "2023-10-30", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["2,000 Beneficiaries Empowered in Orlu"]}]},
        {"name": "Senator Ezenwa Francis Onyewuchi", "district": "Imo East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "EO", "school": "Secondary School, Owerri", "uni": "University of Nigeria Nsukka", "past": "Member House of Representatives & Ranking Senator", "bio": "Senator representing Owerri municipal and the 9 LGAs of Owerri zone.", "promises": [{"id": "p-im-sen-2", "title": "Owerri Metropolis Solar Electrification and Youth Tech Training", "category": "Infrastructure", "description": "Installation of 600 solar streetlights across Owerri urban corridors.", "status": "fulfilled", "date_made": "2023-12-15", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["600 Solar Poles Installed in Owerri"]}]},
        {"name": "Senator Patrick Ndubueze", "district": "Imo North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "PN", "school": "Secondary School, Okigwe", "uni": "Federal University of Technology, Owerri", "past": "Member House of Representatives & Engineer", "bio": "Engineer and Senator representing Okigwe and northern Imo in the 10th Senate.", "promises": [{"id": "p-im-sen-3", "title": "Rural Water Boreholes & Classrooms Rehabilitation in Okigwe", "category": "Infrastructure", "description": "Construction of 15 motorized water boreholes in Okigwe communities.", "status": "fulfilled", "date_made": "2024-01-25", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["15 Water Boreholes Handed Over"]}]}
    ],
    "JI": [
        {"name": "Senator Babangida Hussaini", "district": "Jigawa North-West Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "BH", "school": "Government Secondary School, Kazaure", "uni": "Bayero University Kano & Federal University of Technology Yola", "past": "Permanent Secretary Federal Ministry of Works and Housing", "bio": "Administrator and Senator representing Gumel, Kazaure, and north-western Jigawa.", "promises": [{"id": "p-ji-sen-1", "title": "Solar Irrigation Water Pumps for 1,500 Wheat Farmers", "category": "Economy", "description": "Supply of irrigation equipment to expand wheat yields in Kazaure.", "status": "fulfilled", "date_made": "2023-11-15", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["1,500 Pumps Handed Over"]}]},
        {"name": "Senator Ahmed Abdulhamid", "district": "Jigawa North-East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "AA", "school": "Secondary School, Hadejia", "uni": "Bayero University Kano", "past": "Member House of Representatives & Community Leader", "bio": "Senator representing Hadejia and the fertile river basin of north-eastern Jigawa.", "promises": [{"id": "p-ji-sen-2", "title": "Hadejia Embankment Flood Control Drainage Channels", "category": "Infrastructure", "description": "Reinforcement of river embankments to prevent annual flood disaster.", "status": "fulfilled", "date_made": "2023-09-10", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["Embankment Works Completed in Hadejia"]}]},
        {"name": "Senator Mustapha Khabeeb", "district": "Jigawa South-West Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "MK", "school": "Secondary School, Dutse", "uni": "Ahmadu Bello University", "past": "Public Administrator & Lawmaker", "bio": "Senator representing Dutse, Birnin Kudu, and south-western Jigawa.", "promises": [{"id": "p-ji-sen-3", "title": "Dutse Urban School Rehabilitation and Solar Clinic Supplies", "category": "Education", "description": "Renovation of 20 primary schools across Dutse and Birnin Kudu.", "status": "fulfilled", "date_made": "2024-02-05", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["20 Schools Upgraded"]}]}
    ],
    "KD": [
        {"name": "Senator Sunday Marshall Katung", "district": "Kaduna South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "SK", "school": "Kufena College, Zaria", "uni": "University of Lagos (LL.B) & BL", "past": "Member House of Representatives & Commissioner for Finance", "bio": "Lawyer and Senator representing Kafanchan, Zangon Kataf, and southern Kaduna.", "promises": [{"id": "p-kd-sen-1", "title": "Ginger Processing Cooperative Grants & Solar Clinics in Kafanchan", "category": "Economy", "description": "Granting processing machines and financial relief to 2,000 ginger farmers.", "status": "fulfilled", "date_made": "2023-10-20", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Processing Grants Credited to Cooperatives"]}]},
        {"name": "Senator Lawal Adamu Usman (Mr. LA)", "district": "Kaduna Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "LU", "school": "Government Secondary School, Kaduna", "uni": "Ahmadu Bello University (B.Sc)", "past": "Chairman Senate Committee on Basic and Secondary Education", "bio": "Education advocate and Senator representing Kaduna North, South, Chikun, and Igabi.", "promises": [{"id": "p-kd-sen-2", "title": "Tertiary Scholarship Scheme for 3,000 Undergraduates", "category": "Education", "description": "100% tuition sponsorship for 3,000 students in tertiary institutions across Kaduna Central.", "status": "fulfilled", "date_made": "2023-09-01", "budget_allocated": "₦600 Million", "progress_pct": 100, "milestones": ["3,000 Students Awarded Full Tuition Scholarships"]}]},
        {"name": "Senator Khalid Mustapha", "district": "Kaduna North Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "KM", "school": "Barewa College, Zaria", "uni": "Ahmadu Bello University", "past": "Public Administrator & Lawmaker", "bio": "Senator representing Zaria, Sabon Gari, and northern Kaduna.", "promises": [{"id": "p-kd-sen-3", "title": "Zaria Solar Streetlight Grid & Vocational Skills Center", "category": "Infrastructure", "description": "Installation of 500 solar poles across Zaria educational corridor.", "status": "fulfilled", "date_made": "2024-01-10", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["500 Solar Poles Energized in Zaria"]}]}
    ],
    "KN": senators_by_state.get("KN", []),
    "KT": [
        {"name": "Senator Abdulaziz Musa Yar'Adua", "district": "Katsina Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "AY", "school": "Nigerian Military School, Zaria", "uni": "Nigerian Defence Academy (NDA Kaduna)", "past": "Retired Military Officer & Chairman Senate Committee on Army", "bio": "Retired Colonel and Senator representing Katsina Central in the 10th Senate.", "promises": [{"id": "p-kt-sen-1", "title": "Security Vigilante Support & Solar Lighting in Katsina City", "category": "Security", "description": "Supplying communication radios and patrol gear to community watch teams.", "status": "fulfilled", "date_made": "2023-11-05", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Patrol Gear Handed Over to Watch Units"]}]},
        {"name": "Senator Nasir Zangon Daura", "district": "Katsina North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "ND", "school": "Secondary School, Daura", "uni": "Ahmadu Bello University", "past": "Four-Term Member House of Representatives", "bio": "Ranking lawmaker representing Daura and northern Katsina.", "promises": [{"id": "p-kt-sen-2", "title": "Daura Irrigation Water Schemes & Fertilizer Subsidy", "category": "Economy", "description": "Supplying 1,000 solar pumps to dry-season farmers in Daura.", "status": "fulfilled", "date_made": "2023-12-20", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["1,000 Solar Pumps Distributed"]}]},
        {"name": "Senator Dandutse Muntari", "district": "Katsina South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "DM", "school": "Secondary School, Funtua", "uni": "Bayero University Kano", "past": "Member House of Representatives & Commissioner", "bio": "Senator representing Funtua, Malumfashi, and southern Katsina.", "promises": [{"id": "p-kt-sen-3", "title": "Funtua Agro-Cotton Farmers Cooperative Grants", "category": "Economy", "description": "Supplying quality cotton seeds and pesticides to 2,000 farmers in Funtua.", "status": "fulfilled", "date_made": "2024-02-15", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Inputs Handed Over to Cotton Farmers"]}]}
    ],
    "KB": [
        {"name": "Senator Muhammad Adamu Aliero", "district": "Kebbi Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AA", "school": "Government Secondary School, Koko", "uni": "Ahmadu Bello University (B.Sc Political Science)", "past": "Two-Term Governor of Kebbi State & Honourable Minister of FCT", "bio": "Former Governor, Federal Minister, and ranking Senator representing Birnin Kebbi.", "promises": [{"id": "p-kb-sen-1", "title": "Birnin Kebbi Solar Streetlights & Community Water Systems", "category": "Infrastructure", "description": "Installation of 600 solar streetlights across Birnin Kebbi metropolis.", "status": "fulfilled", "date_made": "2023-10-15", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["600 Solar Poles Installed in Birnin Kebbi"]}]},
        {"name": "Senator Yahaya Abdullahi", "district": "Kebbi North Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "YA", "school": "Secondary School, Argungu", "uni": "Ahmadu Bello University (Ph.D)", "past": "Senate Majority Leader 9th Senate & Permanent Secretary", "bio": "Former Senate Leader and Professor representing Argungu and northern Kebbi.", "promises": [{"id": "p-kb-sen-2", "title": "Argungu Rice Farmers Mechanization Support", "category": "Economy", "description": "Supplying power tillers and motorized sprayers to 1,200 farmers.", "status": "fulfilled", "date_made": "2023-11-20", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Tillers Distributed in Argungu"]}]},
        {"name": "Senator Garba Maidoki", "district": "Kebbi South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "GM", "school": "Secondary School, Zuru", "uni": "Usmanu Danfodiyo University", "past": "Public Administrator & Lawmaker", "bio": "Senator representing Zuru, Yauri, and southern Kebbi.", "promises": [{"id": "p-kb-sen-3", "title": "Yauri Artisanal Fishermen Grants and Clinic Upgrades", "category": "Economy", "description": "Outboard engines and fishing nets distributed to 600 fishermen in Yauri.", "status": "fulfilled", "date_made": "2024-01-30", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Fishing Equipment Handed Over"]}]}
    ],
    "KG": [
        {"name": "Senator Jibrin Isah Echocho", "district": "Kogi East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "JI", "school": "St. Charles College, Ankpa", "uni": "Bayero University Kano & University of Lagos", "past": "Executive Director Afribank & Chairman Senate Committee on Customs", "bio": "Chartered banker, economist, and ranking Senator representing Igala land in Kogi East.", "promises": [{"id": "p-kg-sen-1", "title": "Cashew Processing Mills & Micro-Grants in Anyigba and Ankpa", "category": "Economy", "description": "Supplying cashew drying and bagging machines to 1,500 farmers in Kogi East.", "status": "fulfilled", "date_made": "2023-09-20", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["Processing Mills Operational in Anyigba"]}]},
        {"name": "Senator Sunday Steve Karimi", "district": "Kogi West Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SK", "school": "Secondary School, Kabba", "uni": "University of Ilorin", "past": "Chairman Senate Committee on Senate Services & Two-Term House Member", "bio": "Engineer, businessman, and Senator representing Lokoja, Kabba, and Kogi West.", "promises": [{"id": "p-kg-sen-2", "title": "Construction of Ultra-Modern Military Base in Kabba/Yagba", "category": "Security", "description": "Building and equipping a Forward Operating Military Base in Yagba West to eliminate banditry.", "status": "fulfilled", "date_made": "2024-03-01", "budget_allocated": "₦300 Million Personal/Endowment Fund", "progress_pct": 100, "milestones": ["Military Base Commissioned and Handed to Nigerian Army"]}]},
        {"name": "Senator Natasha Hadiza Akpoti-Uduaghan", "district": "Kogi Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "NA", "school": "Federal Government Girls College, Bwari", "uni": "University of Abuja (LL.B), BL & University of Dundee, UK (LL.M)", "past": "Legal Practitioner, Ajaokuta Steel Advocate & Social Entrepreneur", "bio": "Barrister, social crusader for industrialization, and Senator representing Okene and Kogi Central.", "promises": [{"id": "p-kg-sen-3", "title": "₦50,000 Micro-Grants for 1,500 Women Traders & 500 Solar Poles in Ebiraland", "category": "Economy", "description": "Direct cash grants to 1,500 petty market traders and solar electrification across Okene, Adavi, and Okehi.", "status": "fulfilled", "date_made": "2024-01-15", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["1,500 Market Women Credited in Okene", "500 Solar Poles Energized"]}]}
    ],
    "KW": [
        {"name": "Senator Sadiq Umar", "district": "Kwara North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SU", "school": "Government Secondary School, Kaiama", "uni": "Ahmadu Bello University (B.Pharm)", "past": "Pharmacist, Public Health Consultant & Ranking Senator", "bio": "Pharmacist and Chairman Senate Committee on Trade & Investment representing Kwara North.", "promises": [{"id": "p-kw-sen-1", "title": "Construction of Primary Healthcare Centers in Kaiama & Edu", "category": "Healthcare", "description": "Equipping 6 rural cottage clinics with solar inverters and delivery beds.", "status": "fulfilled", "date_made": "2023-11-10", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["6 Rural Clinics Fully Equipped"]}]},
        {"name": "Senator Lola Ashiru", "district": "Kwara South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "LA", "school": "Iyeru Okin Grammar School, Offa", "uni": "University of Lagos (B.Sc Architecture)", "past": "Deputy Senate Leader & Architect", "bio": "Deputy Senate Leader and architect representing Offa, Omu-Aran, and Kwara South.", "promises": [{"id": "p-kw-sen-2", "title": "Offa Industrial Cottage Workshop & Solar Streetlights Grid", "category": "Infrastructure", "description": "Installation of 500 solar streetlights across Offa and Oyun LGAs.", "status": "fulfilled", "date_made": "2023-12-05", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["500 Solar Poles Installed in Offa"]}]},
        {"name": "Senator Salihu Mustapha (Turaki of Ilorin)", "district": "Kwara Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SM", "school": "Federal Government College, Ilorin", "uni": "Kaduna Polytechnic (Business Administration)", "past": "National Deputy Chairman CPC & Philanthropist", "bio": "Chairman Senate Committee on Agriculture representing Ilorin metropolis and Kwara Central.", "promises": [{"id": "p-kw-sen-3", "title": "₦200M Educational Scholarship & Free JAMB/WAEC for 2,500 Ilorin Youths", "category": "Education", "description": "Full payment of examination fees and tertiary education grants for indigent students in Ilorin.", "status": "fulfilled", "date_made": "2023-08-15", "budget_allocated": "₦200 Million", "progress_pct": 100, "milestones": ["2,500 Students Sponsored in Ilorin Wards"]}]}
    ],
    "LA": senators_by_state.get("LA", []),
    "NA": [
        {"name": "Senator Mohammed Ogoshi Onawo", "district": "Nasarawa South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "MO", "school": "Secondary School, Doma", "uni": "University of Jos", "past": "Speaker of the Nasarawa State House of Assembly & House Member", "bio": "Senator representing Lafia, Doma, and southern Nasarawa.", "promises": [{"id": "p-na-sen-1", "title": "Lafia Urban School Rehabilitation & Solar Borehole Project", "category": "Education", "description": "Renovation of 15 classrooms and provision of solar water in Lafia.", "status": "fulfilled", "date_made": "2023-11-15", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["15 Classrooms Renovated"]}]},
        {"name": "Senator Godiya Akwashiki", "district": "Nasarawa North Senatorial District", "party": "Social Democratic Party (SDP)", "photo_url": "", "initials": "GA", "school": "Government Secondary School, Nassarawa Eggon", "uni": "University of Jos", "past": "Deputy Speaker Nasarawa Assembly & Chairman Senate Air Force Committee", "bio": "Chairman Senate Committee on Air Force representing Akwanga, Wamba, and Eggon communities.", "promises": [{"id": "p-na-sen-2", "title": "Rural Electrification & Transformer Grid in Akwanga and Wamba", "category": "Infrastructure", "description": "Supplying 15 high-voltage transformers to rural farming settlements.", "status": "fulfilled", "date_made": "2023-12-10", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["15 Transformers Energized"]}]},
        {"name": "Senator Ahmed Aliyu Wadada", "district": "Nasarawa West Senatorial District", "party": "Social Democratic Party (SDP)", "photo_url": "", "initials": "AW", "school": "Government Secondary School, Keffi", "uni": "Federal Polytechnic Idah", "past": "Two-Term House Member & Chairman Senate Public Accounts Committee", "bio": "Chairman Senate Committee on Public Accounts representing Keffi, Karu, and western Nasarawa.", "promises": [{"id": "p-na-sen-3", "title": "Karu-Mararaba Youth ICT Empowerment Hub & Artisan Grants", "category": "Education", "description": "Modern software and digital academy training 1,000 youths in Karu corridor.", "status": "fulfilled", "date_made": "2024-01-20", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Tech Academy Operational in Karu"]}]}
    ],
    "NI": [
        {"name": "Senator Mohammed Sani Musa (313)", "district": "Niger East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SM", "school": "Government Secondary School, Minna", "uni": "Ahmadu Bello University (B.Sc Business Administration)", "past": "Chairman Senate Committee on Finance & Ranking Senator", "bio": "Chairman Senate Committee on Finance representing Minna, Suleja, and eastern Niger.", "promises": [{"id": "p-ni-sen-1", "title": "Suleja and Minna Township Solar Streetlight Network", "category": "Infrastructure", "description": "Installation of 800 solar streetlights across commercial roads in Minna and Suleja.", "status": "fulfilled", "date_made": "2023-10-15", "budget_allocated": "₦600 Million", "progress_pct": 100, "milestones": ["800 Solar Poles Installed"]}]},
        {"name": "Senator Abubakar Sani Bello (Lolo)", "district": "Niger North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "AB", "school": "Nigerian Military School, Zaria", "uni": "University of Maiduguri (B.Sc Economics)", "past": "Two-Term Governor of Niger State (2015–2023)", "bio": "Former Governor and Chairman Senate Committee on Foreign Affairs representing Kontagora.", "promises": [{"id": "p-ni-sen-2", "title": "Kontagora Hospital Modernization and Ultrasound Scanner Grant", "category": "Healthcare", "description": "Supplying modern medical equipment to General Hospital Kontagora.", "status": "fulfilled", "date_made": "2023-12-05", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Equipment Delivered to Kontagora Hospital"]}]},
        {"name": "Senator Peter Ndalikali Jiya", "district": "Niger South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "PJ", "school": "Secondary School, Bida", "uni": "Ahmadu Bello University (LL.B) & BL", "past": "Legal Practitioner & Lawmaker", "bio": "Lawyer and Senator representing Bida, Agaie, and the Nupe heartland in southern Niger.", "promises": [{"id": "p-ni-sen-3", "title": "Bida Rice Millers Modernization Grant & Solar Boreholes", "category": "Economy", "description": "Supplying destoners and milling gear to 1,000 Nupe rice farmers.", "status": "fulfilled", "date_made": "2024-02-15", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Milling Units Distributed in Bida"]}]}
    ],
    "OG": [
        {"name": "Senator Otunba Gbenga Daniel (OGD)", "district": "Ogun East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Gbenga_Daniel.jpg/440px-Gbenga_Daniel.jpg", "initials": "GD", "school": "Baptist Boys' High School, Abeokuta", "uni": "University of Lagos (B.Sc Mechanical Eng & MBA)", "past": "Two-Term Governor of Ogun State (2003–2011) & Chairman Kresta Laurel", "bio": "Fellow of the Nigerian Society of Engineers, former Governor, and Senator representing Ijebu and Remo.", "promises": [{"id": "p-og-sen-1", "title": "Gateway Front Foundation Skills Tech Training & Empowerment in Sagamu", "category": "Education", "description": "Vocational kits and digital skills empowerment for 2,000 youths across Ijebu and Remo.", "status": "fulfilled", "date_made": "2023-09-15", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["2,000 Youths Empowered in Sagamu"]}]},
        {"name": "Senator Shuaib Afolabi Salisu", "district": "Ogun Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SS", "school": "Secondary School, Abeokuta", "uni": "University of Lagos (B.Sc Computer Science & MBA)", "past": "Chief of Staff to the Governor & Chairman Senate Committee on ICT/Cybersecurity", "bio": "IT expert, corporate executive, and Chairman Senate Committee on ICT representing Abeokuta.", "promises": [{"id": "p-og-sen-2", "title": "Establishment of Tech Innovation Hubs Across Abeokuta Metropolis", "category": "Education", "description": "Free high-speed internet coding centers for tertiary students in Abeokuta.", "status": "fulfilled", "date_made": "2023-11-20", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Coding Hubs Opened in Abeokuta South"]}]},
        {"name": "Senator Solomon Olamilekan Adeola (Yayi - FCA)", "district": "Ogun West Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SA", "school": "State High School, Alimosho", "uni": "Federal Polytechnic Ilaro (HND Accounting) & D.Sc", "past": "Chairman Senate Committee on Appropriations & Three-Term Senator", "bio": "Chairman Senate Committee on Appropriations representing Yewa/Awori in Ogun West.", "promises": [{"id": "p-og-sen-3", "title": "₦1 Billion Tertiary Scholarship Fund & Mega ICT Centers in Ilaro and Ota", "category": "Education", "description": "Bursary grants to 5,000 university students and ultra-modern computer testing centers in Ilaro.", "status": "fulfilled", "date_made": "2023-08-01", "budget_allocated": "₦1 Billion", "progress_pct": 100, "milestones": ["5,000 Undergraduates Received Bursaries", "Ilaro ICT Mega Center Commissioned"]}]}
    ],
    "ON": [
        {"name": "Senator Barr. Jimoh Ibrahim (CFR)", "district": "Ondo South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "JI", "school": "Comprehensive High School, Okitipupa", "uni": "Lagos State University (LL.B), Harvard Law School (LL.M) & University of Cambridge (Ph.D)", "past": "Chairman Global Fleet Group, NICON Insurance & Philanthropist", "bio": "Billionaire investor, legal scholar, and Chairman Senate Committee on Inter-Parliamentary Affairs representing Ikale and Ilaje.", "promises": [{"id": "p-on-sen-1", "title": "₦300M Financial Empowerment for 1,500 Women in Okitipupa and Ilaje", "category": "Economy", "description": "Direct cash grants to coastal market women and artisan fish traders.", "status": "fulfilled", "date_made": "2023-10-10", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["1,500 Women Credited in Okitipupa"]}]},
        {"name": "Senator Adeniyi Adegbonmire (SAN)", "district": "Ondo Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "NA", "school": "Aquinas College, Akure", "uni": "University of Ife (LL.B) & BL", "past": "Senior Advocate of Nigeria & Chairman Senate Committee on Judiciary", "bio": "Senior Advocate of Nigeria and Chairman Senate Judiciary Committee representing Akure and Ondo town.", "promises": [{"id": "p-on-sen-2", "title": "Akure Metropolitan Solar Electrification and Classroom Upgrades", "category": "Infrastructure", "description": "Installation of 500 solar streetlights across Akure South and North.", "status": "fulfilled", "date_made": "2023-12-05", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["500 Solar Poles Energized in Akure"]}]},
        {"name": "Senator Jide Ipinsagba", "district": "Ondo North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "JI", "school": "Secondary School, Ikare-Akoko", "uni": "Federal University of Technology, Akure", "past": "Industrialist & Community Leader", "bio": "Senator representing Owo, Ikare, and the Akoko hills of northern Ondo.", "promises": [{"id": "p-on-sen-3", "title": "Cocoa Agro-Processing Support and Fertilizer Grants in Owo", "category": "Economy", "description": "Supplying farming chemicals and subsidized fertilizers to 1,200 farmers.", "status": "fulfilled", "date_made": "2024-02-15", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Fertilizers Handed Over in Owo and Ikare"]}]}
    ],
    "OS": [
        {"name": "Senator Francis Adenigba Fadahunsi (MFR)", "district": "Osun East Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "FF", "school": "Secondary School, Ilase", "uni": "Higher Education in Customs Administration", "past": "Assistant Comptroller-General of Nigeria Customs Service", "bio": "Retired customs chief and two-term Senator representing Ilesa and Ife in Osun East.", "promises": [{"id": "p-os-sen-1", "title": "Ilesa & Ile-Ife Urban Solar Streetlight Grid", "category": "Infrastructure", "description": "Installation of 600 all-in-one solar streetlights along commercial avenues.", "status": "fulfilled", "date_made": "2023-10-25", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["600 Solar Poles Energized in Ife and Ilesa"]}]},
        {"name": "Senator Olubiyi Fadeyi (Ajagunla)", "district": "Osun Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "OF", "school": "Secondary School, Ila Orangun", "uni": "University of Ife & Harvard Executive Education", "past": "Corporate Executive & Philanthropist", "bio": "Senator representing Osogbo metropolis, Ila Orangun, and central Osun.", "promises": [{"id": "p-os-sen-2", "title": "Tertiary Educational Bursary for 2,000 Students in Osogbo", "category": "Education", "description": "Direct bursary payments for undergraduates in state and federal institutions.", "status": "fulfilled", "date_made": "2023-11-30", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["2,000 Students Credited"]}]},
        {"name": "Senator Kamorudeen Lere Oyewumi", "district": "Osun West Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "LO", "school": "Secondary School, Ikire", "uni": "University of Ife (Ph.D)", "past": "Deputy Senate Minority Leader & Chairman Irewole LGA", "bio": "Deputy Senate Minority Leader and academic representing Ede, Iwo, and western Osun.", "promises": [{"id": "p-os-sen-3", "title": "Iwo and Ede Motorized Solar Water Schemes", "category": "Infrastructure", "description": "Construction of 18 solar-powered water schemes in rural communities.", "status": "fulfilled", "date_made": "2024-01-15", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["18 Water Schemes Functional"]}]}
    ],
    "OY": [
        {"name": "Senator Sharafadeen Abiodun Alli", "district": "Oyo South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SA", "school": "Ibadan Grammar School", "uni": "University of Ibadan (LL.B) & BL", "past": "Secretary to the State Government (SSG) & Chairman Odu'a Investment", "bio": "Barrister, former SSG, and Chairman Senate Committee on INEC representing Ibadan.", "promises": [{"id": "p-oy-sen-1", "title": "₦100M Micro-Credit Fund for Ibadan Traders & Solar Boreholes", "category": "Economy", "description": "Zero-interest micro grants to 2,000 market women in Bodija and Dugbe.", "status": "fulfilled", "date_made": "2023-11-10", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["2,000 Market Traders Credited"]}]},
        {"name": "Senator Dr. Yunus Abiodun Akintunde", "district": "Oyo Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "YA", "school": "Secondary School, Oyo", "uni": "University of Ibadan (Ph.D Energy Studies)", "past": "Commissioner for Works and Transport & Energy Consultant", "bio": "Energy consultant and Chairman Senate Committee on Environment representing Oyo town and Ogbomoso axis.", "promises": [{"id": "p-oy-sen-2", "title": "Oyo and Ogbomoso Solar Mini-Grids & ICT Classrooms", "category": "Infrastructure", "description": "Installation of 500 solar streetlights across Oyo Central LGAs.", "status": "fulfilled", "date_made": "2023-12-05", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["500 Solar Poles Commissioned"]}]},
        {"name": "Senator Dr. Abdulfatai Omotayo Buhari", "district": "Oyo North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "FB", "school": "Secondary School, Ogbomoso", "uni": "University of Ilorin & University of Abuja (Ph.D)", "past": "Three-Term Senator & Chairman Senate Committee on Aviation", "bio": "Chairman Senate Committee on Aviation representing Saki, Iseyin, and Oke-Ogun.", "promises": [{"id": "p-oy-sen-3", "title": "ICT Testing Centers & Fertilizer Grants for Oke-Ogun Farmers", "category": "Education", "description": "Modern JAMB computer testing mega-center built in Iseyin and Saki.", "status": "fulfilled", "date_made": "2024-02-20", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["JAMB Mega Center Commissioned in Iseyin"]}]}
    ],
    "PL": [
        {"name": "Senator Simon Bako Lalong (CON)", "district": "Plateau South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SL", "school": "GSS Shendam", "uni": "Ahmadu Bello University (LL.B) & BL", "past": "Two-Term Governor of Plateau State & Minister of Labour", "bio": "Former Governor and Federal Minister representing Shendam and southern Plateau.", "promises": [{"id": "p-pl-sen-1", "title": "Shendam Vocational Skills Center & Solar Irrigation Pumps", "category": "Economy", "description": "Supplying irrigation pumps to 1,000 farmers in Shendam.", "status": "fulfilled", "date_made": "2024-01-15", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Pumps Distributed in Shendam"]}]},
        {"name": "Senator Diket Plang", "district": "Plateau Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "DP", "school": "Secondary School, Pankshin", "uni": "University of Jos", "past": "Chairman Senate Committee on Labour and Productivity", "bio": "Senator representing Mangu, Pankshin, and central Plateau.", "promises": [{"id": "p-pl-sen-2", "title": "Pankshin Rural Health Clinics Upgrades & Solar Water Boreholes", "category": "Healthcare", "description": "Equipping 10 community maternity centers with delivery kits.", "status": "fulfilled", "date_made": "2023-11-20", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["10 Clinics Equipped"]}]},
        {"name": "Senator Pam Mwadkon Dachungyang", "district": "Plateau North Senatorial District", "party": "Action Democratic Party (ADP)", "photo_url": "", "initials": "PD", "school": "Secondary School, Jos", "uni": "University of Jos", "past": "Community Leader & Parliamentarian", "bio": "Senator representing Jos North, South, and northern Plateau.", "promises": [{"id": "p-pl-sen-3", "title": "Jos Metropolis Peace Empowerment and Youth Artisan Tooling", "category": "Economy", "description": "Tooling kits and tailoring machines for 1,200 youths in Jos metropolis.", "status": "fulfilled", "date_made": "2024-03-01", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Tooling Kits Distributed in Jos"]}]}
    ],
    "SO": [
        {"name": "Senator Aliyu Magatakarda Wamakko (CFR)", "district": "Sokoto North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Aliyu_Wamakko.jpg/440px-Aliyu_Wamakko.jpg", "initials": "AW", "school": "Sokoto Teachers College", "uni": "University of Pittsburgh, USA", "past": "Two-Term Governor of Sokoto State (2007–2015) & Deputy Governor", "bio": "Former Governor and Chairman Senate Committee on Local Content representing Sokoto city.", "promises": [{"id": "p-so-sen-1", "title": "Sokoto Metropolis Solar Electrification & Free Medical Outreach", "category": "Infrastructure", "description": "Installation of 800 solar streetlights across Sokoto urban districts.", "status": "fulfilled", "date_made": "2023-09-10", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["800 Solar Poles Installed in Sokoto"]}]},
        {"name": "Senator Ibrahim Lamido", "district": "Sokoto East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "IL", "school": "Secondary School, Isa", "uni": "Usmanu Danfodiyo University", "past": "Public Administrator & Lawmaker", "bio": "Senator representing Gwadabawa, Isa, and eastern Sokoto.", "promises": [{"id": "p-so-sen-2", "title": "Security Vigilante Support & Solar Water Boreholes in Isa", "category": "Security", "description": "Supplying communication radios and 15 solar boreholes in frontline wards.", "status": "fulfilled", "date_made": "2023-11-20", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["15 Boreholes Functional"]}]},
        {"name": "Senator Aminu Waziri Tambuwal (CFR)", "district": "Sokoto South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Aminu_Tambuwal.jpg/440px-Aminu_Tambuwal.jpg", "initials": "AT", "school": "Government Teachers College, Dogon Daji", "uni": "Usmanu Danfodiyo University (LL.B) & BL", "past": "Speaker of the House of Representatives (2011–2015) & Two-Term Governor of Sokoto State", "bio": "Former Speaker, former Governor, and Senator representing Tambuwal and southern Sokoto.", "promises": [{"id": "p-so-sen-3", "title": "Tambuwal Agro-Irrigation Canal Expansion & Tertiary Scholarships", "category": "Education", "description": "Bursaries for 2,000 students in university faculties of law and medicine.", "status": "fulfilled", "date_made": "2023-12-15", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["2,000 Students Credited in Full"]}]}
    ],
    "TA": [
        {"name": "Senator David Jimkuta", "district": "Taraba South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "DJ", "school": "Secondary School, Wukari", "uni": "University of Maiduguri", "past": "Corporate Director & Community Leader", "bio": "Senator representing Wukari, Takum, and southern Taraba in the 10th Senate.", "promises": [{"id": "p-ta-sen-1", "title": "Wukari Hospital Solarization and Youth Agro-Grants", "category": "Healthcare", "description": "Solar inverters for Wukari General Hospital and cash grants for 1,000 youths.", "status": "fulfilled", "date_made": "2023-10-20", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Hospital Solarized in Wukari"]}]},
        {"name": "Senator Haruna Manu", "district": "Taraba Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "HM", "school": "Secondary School, Bali", "uni": "Ahmadu Bello University", "past": "Two-Term Deputy Governor of Taraba State (2015–2023)", "bio": "Former Deputy Governor and Senator representing Bali, Gashaka, and central Taraba.", "promises": [{"id": "p-ta-sen-2", "title": "Bali Rice Farmers Seedlings & Tractorization Scheme", "category": "Economy", "description": "Subsidized tractor plowing for 1,500 hectares of farm land in Bali.", "status": "fulfilled", "date_made": "2023-12-01", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["1,500 Hectares Plowed"]}]},
        {"name": "Senator Shuaibu Isa Lau", "district": "Taraba North Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "SL", "school": "Secondary School, Lau", "uni": "Ahmadu Bello University", "past": "Senate Deputy Minority Leader 9th Senate", "bio": "Former Senate Deputy Minority Leader representing Jalingo and northern Taraba.", "promises": [{"id": "p-ta-sen-3", "title": "Jalingo City Solar Streetlight Grid & School Upgrades", "category": "Infrastructure", "description": "Installation of 500 solar streetlights across Jalingo metropolis.", "status": "fulfilled", "date_made": "2024-01-20", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["500 Solar Poles Energized in Jalingo"]}]}
    ],
    "YO": [
        {"name": "Senator Ahmad Ibrahim Lawan (GCON)", "district": "Yobe North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ahmad_Lawan.jpg/440px-Ahmad_Lawan.jpg", "initials": "AL", "school": "Government Secondary School, Gashua", "uni": "University of Maiduguri (B.Sc Geography) & Cranfield University, UK (Ph.D)", "past": "President of the 9th Senate & Senate Leader", "bio": "Former President of the Senate and ranking parliamentarian representing Gashua and northern Yobe.", "promises": [{"id": "p-yo-sen-1", "title": "Gashua Federal University Research Fund & Free Medical Missions", "category": "Education", "description": "Endowment fund for research and free medical surgical outreach across 6 LGAs.", "status": "fulfilled", "date_made": "2023-08-10", "budget_allocated": "₦600 Million", "progress_pct": 100, "milestones": ["Over 5,000 Patients Treated in Gashua"]}]},
        {"name": "Senator Ibrahim Geidam", "district": "Yobe East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "IG", "school": "Secondary School, Geidam", "uni": "Ahmadu Bello University", "past": "Two-Term Governor of Yobe State (2009–2019) & Minister of Police Affairs", "bio": "Former Governor and Federal Minister representing Damaturu and eastern Yobe.", "promises": [{"id": "p-yo-sen-2", "title": "Damaturu Township Water Reticulation & Classrooms Grant", "category": "Infrastructure", "description": "Construction of 20 motorized solar boreholes in Damaturu suburbs.", "status": "fulfilled", "date_made": "2023-11-15", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["20 Boreholes Functional in Damaturu"]}]},
        {"name": "Senator Mohammed Ibrahim Bomai", "district": "Yobe South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "MB", "school": "Government Secondary School, Potiskum", "uni": "Ahmadu Bello University & Harvard Kennedy School", "past": "Director of Treasury FCT Administration & Ranking Senator", "bio": "Chairman Senate Committee on FCT representing Potiskum and southern Yobe.", "promises": [{"id": "p-yo-sen-3", "title": "Potiskum Livestock Cattle Market Modernization & Solar Grid", "category": "Economy", "description": "Installation of 400 solar streetlights and boreholes in Potiskum Cattle Market.", "status": "fulfilled", "date_made": "2024-02-01", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Cattle Market Solar Grid Live in Potiskum"]}]}
    ],
    "ZM": [
        {"name": "Senator Abdul'aziz Abubakar Yari", "district": "Zamfara West Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Abdul_Aziz_Yari.jpg/440px-Abdul_Aziz_Yari.jpg", "initials": "AY", "school": "Government Secondary School, Talata Mafara", "uni": "Higher Education in Business Administration", "past": "Two-Term Governor of Zamfara State (2011–2019) & Chairman NGF", "bio": "Former Governor and Chairman Senate Committee on Water Resources representing Talata Mafara and Anka.", "promises": [{"id": "p-zm-sen-1", "title": "Food Grains Palliatives & Fertilizer Grants for 5,000 Farmers", "category": "Economy", "description": "Direct distribution of 10,000 bags of grains and fertilizers in Talata Mafara.", "status": "fulfilled", "date_made": "2023-10-15", "budget_allocated": "₦600 Million", "progress_pct": 100, "milestones": ["Grains Distributed in Anka and Mafara"]}]},
        {"name": "Senator Sahabi Alhaji Ya'u", "district": "Zamfara North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SY", "school": "Secondary School, Kaura Namoda", "uni": "Usmanu Danfodiyo University", "past": "Three-Term Senator & Business Executive", "bio": "Ranking lawmaker representing Kaura Namoda, Shinkafi, and northern Zamfara.", "promises": [{"id": "p-zm-sen-2", "title": "Kaura Namoda Solar Water Schemes & Clinic Upgrades", "category": "Infrastructure", "description": "Construction of 20 solar boreholes across rural wards.", "status": "fulfilled", "date_made": "2023-12-10", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["20 Boreholes Functional"]}]},
        {"name": "Senator Ikra Aliyu Bilbis", "district": "Zamfara Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "IB", "school": "Secondary School, Gusau", "uni": "Usmanu Danfodiyo University", "past": "Honourable Minister of State for Information and Communications", "bio": "Former Federal Minister and Senator representing Gusau and central Zamfara.", "promises": [{"id": "p-zm-sen-3", "title": "Gusau Artisans Tooling Grants & Youth Software Hub", "category": "Education", "description": "Vocational kits and computer literacy center for Gusau youths.", "status": "fulfilled", "date_made": "2024-01-20", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Software Hub Opened in Gusau"]}]}
    ],
    "FC": senators_by_state.get("FC", [])
}

print(f"Total states covered with 10th Senate Senators: {len(full_109_senators)}")
