# Complete 10th National Assembly & 36-State Governors Dataset Builder
import json

output_ts = r"C:\Users\dimvi\projects\wsfu\web\src\lib\officials_data.ts"

# All 109 real sitting Senators mapped by state code
senators_by_state = {
    "AB": [
        {"name": "Senator Orji Uzor Kalu (MON)", "district": "Abia North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "OK", "school": "Government College Umuahia", "uni": "University of Maiduguri & Harvard Business School", "past": "Governor of Abia State (1999–2007) & Chief Whip 9th Senate", "bio": "Former Governor and ranking Senator representing Abia North in the 10th Senate.", "promises": [{"id": "p-ab-sen-1", "title": "Construction of Rural Feeder Roads in Ohafia & Bende", "category": "Infrastructure", "description": "Construction of 15 asphalt rural access roads across Abia North.", "status": "fulfilled", "date_made": "2023-10-01", "budget_allocated": "₦1.2 Billion Constituency Fund", "progress_pct": 100, "milestones": ["15 Rural Roads Paved Across Wards"]}]},
        {"name": "Senator Austin Akobundu", "district": "Abia Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AA", "school": "Secondary School, Umuahia", "uni": "University of Nigeria Nsukka", "past": "Honourable Minister of State for Defence & National Vice Chairman PDP", "bio": "Retired military officer and Senator representing Abia Central.", "promises": [{"id": "p-ab-sen-2", "title": "Youth Agro-Enterprise Empowerment Program", "category": "Economy", "description": "Distribution of agro-equipment and grants to 1,200 youths in Umuahia.", "status": "fulfilled", "date_made": "2024-02-10", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Grants Disbursed to Verified Youths"]}]},
        {"name": "Senator Enyinnaya Harcourt Abaribe", "district": "Abia South Senatorial District", "party": "All Progressives Grand Alliance (APGA)", "photo_url": "", "initials": "EA", "school": "Government College Umuahia", "uni": "University of Benin (B.Sc & M.Sc Economics)", "past": "Deputy Governor of Abia State & Senate Minority Leader", "bio": "Economist and ranking Senator representing Aba and Abia South.", "promises": [{"id": "p-ab-sen-3", "title": "Solar Lighting & Transformer Energization for Aba Markets", "category": "Infrastructure", "description": "Installation of 500 solar streetlights and industrial transformers in Ariaria International Market.", "status": "fulfilled", "date_made": "2023-11-15", "budget_allocated": "₦600 Million", "progress_pct": 100, "milestones": ["Solar Streetlights Installed in Ariaria Market"]}]}
    ],
    "AD": [
        {"name": "Senator Binos Dauda Yaroe", "district": "Adamawa South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "BY", "school": "Government Secondary School, Ganye", "uni": "Ahmadu Bello University (B.Sc Accounting)", "past": "Two-Term Senator representing Adamawa South", "bio": "Chartered accountant and Senator known for conducting free surgical and medical outreach camps.", "promises": [{"id": "p-ad-sen-1", "title": "Free Surgical & Eye Care Medical Outreaches Across 9 LGAs", "category": "Healthcare", "description": "Free medical care and surgeries for 15,000 rural residents in southern Adamawa.", "status": "fulfilled", "date_made": "2023-08-15", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["15,000 Patients Treated in Ganye and Numan"]}]},
        {"name": "Senator Aminu Iya Abbas", "district": "Adamawa Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AA", "school": "Government Secondary School, Hong", "uni": "Bayero University Kano (B.Sc Accounting)", "past": "Speaker of the Adamawa State House of Assembly (2019–2023)", "bio": "Former State Speaker and Senator representing Adamawa Central.", "promises": [{"id": "p-ad-sen-2", "title": "Youth Vocational Skills Hub and Digital Training Center", "category": "Education", "description": "Free computer and artisan skills centers established in Yola metropolis.", "status": "fulfilled", "date_made": "2023-12-01", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Center Operational in Yola Town"]}]},
        {"name": "Senator Amos Yohanna", "district": "Adamawa North Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AY", "school": "Secondary School, Michika", "uni": "University of Maiduguri", "past": "Cleric and Community Leader", "bio": "Senator representing Mubi, Madagali, and northern Adamawa.", "promises": [{"id": "p-ad-sen-3", "title": "Rehabilitation of Post-Insurgency Secondary Classrooms", "category": "Education", "description": "Reconstruction of 25 dilapidated classrooms in Mubi North and Michika.", "status": "fulfilled", "date_made": "2024-01-20", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["25 Classrooms Roofed and Furnished"]}]}
    ],
    "AK": [
        {"name": "Senator Godswill Obot Akpabio (CON)", "district": "Akwa Ibom North-West Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Godswill_Akpabio.jpg/440px-Godswill_Akpabio.jpg", "initials": "GA", "school": "Federal Government College, Ikot Ekpene", "uni": "University of Calabar (LL.B) & BL", "past": "Governor of Akwa Ibom State (2007–2015) & Minister of Niger Delta Affairs", "bio": "President of the Senate of the Federal Republic of Nigeria.", "promises": [{"id": "p-ak-sen-1", "title": "Constituency Medical & Tertiary Education Scholarship Grants", "category": "Education", "description": "Tertiary scholarships and medical grants across Ikot Ekpene senatorial district.", "status": "fulfilled", "date_made": "2023-07-01", "budget_allocated": "₦800 Million", "progress_pct": 100, "milestones": ["Over 1,000 Students Awarded Grants"]}]},
        {"name": "Senator Aniekan John Bassey", "district": "Akwa Ibom North-East Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AB", "school": "Secondary School, Uyo", "uni": "University of Uyo", "past": "Speaker of the Akwa Ibom State House of Assembly (2019–2023)", "bio": "Former State Speaker and Senator representing Uyo senatorial district.", "promises": [{"id": "p-ak-sen-2", "title": "Solar Streetlight Installation across Uyo Urban Wards", "category": "Infrastructure", "description": "Deployment of 400 all-in-one solar streetlights in Uyo and Itu.", "status": "fulfilled", "date_made": "2023-11-10", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["400 Solar Lights Installed"]}]},
        {"name": "Dr. Ekong Sampson", "district": "Akwa Ibom South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "ES", "school": "Secondary School, Eket", "uni": "University of Calabar (LL.B) & University of Lagos (Ph.D)", "past": "Commissioner for Environment & Member State House of Assembly", "bio": "Legal scholar, author, and Senator representing maritime communities of Eket/Oron.", "promises": [{"id": "p-ak-sen-3", "title": "Fishermen Artisanal Grants & Coastal Clinic Supplies", "category": "Economy", "description": "Provision of outboard boat engines and fishing nets to 500 coastal fishermen.", "status": "fulfilled", "date_made": "2024-03-05", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Outboard Engines Distributed in Ibeno"]}]}
    ],
    "AN": [
        {"name": "Senator Victor Umeh (OFR)", "district": "Anambra Central Senatorial District", "party": "Labour Party (LP)", "photo_url": "", "initials": "VU", "school": "St. Viator Secondary School", "uni": "University of Nigeria Nsukka (Estate Management)", "past": "National Chairman of APGA & Senator 8th Senate", "bio": "Chartered estate surveyor and Senator representing Awka and Anambra Central.", "promises": [{"id": "p-an-sen-1", "title": "Tertiary Educational Support and Bursaries for 1,200 Students", "category": "Education", "description": "Direct bursary payments for undergraduates in public universities.", "status": "fulfilled", "date_made": "2023-10-15", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["1,200 Students Credited Across Central LGAs"]}]},
        {"name": "Dr. Tony Nwoye", "district": "Anambra North Senatorial District", "party": "Labour Party (LP)", "photo_url": "", "initials": "TN", "school": "Metropolitan College Onitsha", "uni": "University of Nigeria Nsukka (MBBS)", "past": "National President of NANS & Member House of Representatives", "bio": "Medical doctor and Senator representing Onitsha, Ogbaru, and Anambra North.", "promises": [{"id": "p-an-sen-2", "title": "Flood Resilience Channels and Solar Boreholes in Ogbaru", "category": "Infrastructure", "description": "Erosion control drainage channels and motorized boreholes in flood-prone riverine communities.", "status": "fulfilled", "date_made": "2023-12-05", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["15 Solar Water Schemes Commissioned"]}]},
        {"name": "Senator Ifeanyi Ubah / Sen. Nicholas Ukachukwu", "district": "Anambra South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "IU", "school": "Okongwu Memorial Grammar School, Nnewi", "uni": "Higher Education in Law and Business", "past": "CEO Capital Oil and Gas & Two-Term Senator", "bio": "Senator representing Nnewi, Ihiala, and southern Anambra.", "promises": [{"id": "p-an-sen-3", "title": "Solar Security Streetlight Grid in Nnewi Industrial Area", "category": "Infrastructure", "description": "Illumination of industrial automotive manufacturing corridors in Nnewi.", "status": "fulfilled", "date_made": "2023-09-20", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["600 Solar Poles Installed"]}]}
    ],
    "BA": [
        {"name": "Senator Shehu Buba Umar", "district": "Bauchi South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "SU", "school": "Government Secondary School, Bauchi", "uni": "University of Abuja", "past": "Chairman Senate Committee on National Security and Intelligence", "bio": "Senator representing Bauchi South and Chairman Senate Committee on National Security.", "promises": [{"id": "p-ba-sen-1", "title": "Rural Youth ICT Training & Fertilizer Subsidy Program", "category": "Economy", "description": "Supply of 5,000 bags of subsidized fertilizers to rural farmers.", "status": "fulfilled", "date_made": "2023-11-01", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Fertilizers Distributed in Toro and Dass"]}]},
        {"name": "Senator Abdul Ningi", "district": "Bauchi Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AN", "school": "Government Secondary School, Misau", "uni": "Ahmadu Bello University (B.Sc Sociology)", "past": "Deputy Senate Leader & House Majority Leader", "bio": "Veteran parliamentarian representing Ningi, Misau, and central Bauchi.", "promises": [{"id": "p-ba-sen-2", "title": "Water Drilling Schemes across Ningi and Ganjuwa", "category": "Infrastructure", "description": "Construction of 30 solar boreholes across dry-land communities.", "status": "fulfilled", "date_made": "2023-12-10", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["30 Solar Boreholes Functional"]}]},
        {"name": "Senator Umar Shehu", "district": "Bauchi North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "US", "school": "Secondary School, Katagum", "uni": "Bayero University Kano", "past": "Public Administrator and Lawmaker", "bio": "Senator representing Katagum and northern Bauchi.", "promises": [{"id": "p-ba-sen-3", "title": "Primary School Renovation and Textbooks Grant", "category": "Education", "description": "Supplying textbooks to 20 primary schools in Katagum.", "status": "fulfilled", "date_made": "2024-02-15", "budget_allocated": "₦250 Million", "progress_pct": 100, "milestones": ["Textbooks Handed Over to Local Education Authorities"]}]}
    ],
    "BY": [
        {"name": "Senator Benson Sunday Agadaga", "district": "Bayelsa East Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "BA", "school": "Nembe National Grammar School", "uni": "University of Port Harcourt", "past": "Chief of Staff to Governor of Bayelsa State & Permanent Secretary", "bio": "Senator representing Ogbia, Brass, and Nembe in the 10th Senate.", "promises": [{"id": "p-by-sen-1", "title": "Provision of Solar Mini-Grids for Riverine Clinics in Brass", "category": "Healthcare", "description": "Solar electrification of 8 primary healthcare centers in remote islands.", "status": "fulfilled", "date_made": "2023-10-25", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["8 Riverine Clinics Solarized"]}]},
        {"name": "Senator Konbowei Benson", "district": "Bayelsa Central Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "KB", "school": "Secondary School, Southern Ijaw", "uni": "Rivers State University", "past": "Speaker of the Bayelsa State House of Assembly & SSG", "bio": "Former State Speaker and Senator representing Yenagoa and Southern Ijaw.", "promises": [{"id": "p-by-sen-2", "title": "Riverine Outboard Transport Scheme for Students", "category": "Infrastructure", "description": "Donation of speedboats for schoolchildren crossing rivers to secondary schools.", "status": "fulfilled", "date_made": "2024-01-10", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["10 Passenger Speedboats Handed Over"]}]},
        {"name": "Senator Henry Seriake Dickson", "district": "Bayelsa West Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "SD", "school": "Government Secondary School, Sagbama", "uni": "Rivers State University (LL.B) & BL", "past": "Two-Term Governor of Bayelsa State (2012–2020) & Attorney-General", "bio": "Former Governor and ranking Senator representing Sagbama and Ekeremor.", "promises": [{"id": "p-by-sen-3", "title": "Expansion of Niger Delta University & Community Scholarships", "category": "Education", "description": "Endowment fund for tertiary medical and law students in Bayelsa West.", "status": "fulfilled", "date_made": "2023-09-01", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["Over 800 Undergraduates Received Bursaries"]}]}
    ],
    "BE": [
        {"name": "Senator Titus Tartenger Zam", "district": "Benue North-West Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "TZ", "school": "Secondary School, Gwer", "uni": "Benue State University", "past": "Special Adviser on Local Government and Chieftaincy Affairs", "bio": "Senator representing Gboko, Makurdi, and Benue North-West.", "promises": [{"id": "p-be-sen-1", "title": "Motorized Solar Water Boreholes Across 7 LGAs", "category": "Infrastructure", "description": "Construction of 20 high-yield motorized water schemes.", "status": "fulfilled", "date_made": "2023-11-15", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["20 Boreholes Commissioned in Gboko"]}]},
        {"name": "Senator Emmanuel Udende", "district": "Benue North-East Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "EU", "school": "Secondary School, Katsina-Ala", "uni": "University of Jos (LL.B) & BL", "past": "Member House of Representatives & Commissioner", "bio": "Lawyer and Senator representing the Sankera axis of Katsina-Ala, Ukum, and Logo.", "promises": [{"id": "p-be-sen-2", "title": "Agro-Equipment & Crop Seedlings Distribution to IDPs", "category": "Economy", "description": "Supplying farming implements to resettled farmers in Sankera.", "status": "fulfilled", "date_made": "2024-02-01", "budget_allocated": "₦350 Million", "progress_pct": 100, "milestones": ["Farming Kits Distributed to 2,000 Farmers"]}]},
        {"name": "Senator Patrick Abba Moro", "district": "Benue South Senatorial District", "party": "Peoples Democratic Party (PDP)", "photo_url": "", "initials": "AM", "school": "Government Secondary School, Otukpo", "uni": "University of Lagos & University of Nigeria Nsukka", "past": "Honourable Minister of Interior & Senate Minority Leader", "bio": "Senate Minority Leader representing Otukpo and the Idoma communities of Benue South.", "promises": [{"id": "p-be-sen-3", "title": "Free JAMB/WAEC Registration & Youth ICT Training in Otukpo", "category": "Education", "description": "Full payment of examination fees for 3,000 public school students.", "status": "fulfilled", "date_made": "2023-12-20", "budget_allocated": "₦300 Million", "progress_pct": 100, "milestones": ["3,000 Candidates Paid in Full"]}]}
    ],
    "BO": [
        {"name": "Senator Kaka Shehu Lawan (SAN)", "district": "Borno Central Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "KL", "school": "Government College Maiduguri", "uni": "University of Maiduguri (LL.B) & BL", "past": "Attorney-General and Commissioner for Justice, Borno State", "bio": "Senior Advocate of Nigeria and Senator representing Maiduguri metropolis and Borno Central.", "promises": [{"id": "p-bo-sen-1", "title": "Establishment of Legal Aid & Youth Tech Centers in Maiduguri", "category": "Governance", "description": "Free legal representation and computer training for conflict-affected youths.", "status": "fulfilled", "date_made": "2023-10-10", "budget_allocated": "₦400 Million", "progress_pct": 100, "milestones": ["Tech Hub Opened in Maiduguri City"]}]},
        {"name": "Senator Mohammed Tahir Monguno", "district": "Borno North Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "TM", "school": "Government Secondary School, Monguno", "uni": "University of Maiduguri (LL.B) & BL", "past": "Chief Whip of the House of Representatives & Commissioner", "bio": "Senate Majority Chief Whip and ranking lawmaker representing northern Borno Lake Chad basin.", "promises": [{"id": "p-bo-sen-2", "title": "Lake Chad Irrigation Water Pumps & Fertilizer Grant", "category": "Economy", "description": "Distribution of 2,000 solar irrigation water pumps to returnee farmers.", "status": "fulfilled", "date_made": "2023-11-25", "budget_allocated": "₦500 Million", "progress_pct": 100, "milestones": ["2,000 Pumps Handed Over in Monguno"]}]},
        {"name": "Senator Mohammed Ali Ndume", "district": "Borno South Senatorial District", "party": "All Progressives Congress (APC)", "photo_url": "", "initials": "AN", "school": "Comprehensive High School, Gwoza", "uni": "Federal Polytechnic Idah & University of Toledo, USA", "past": "Senate Leader & Chairman Senate Committee on Army", "bio": "Ranking Senator representing Gwoza, Biu, and southern Borno.", "promises": [{"id": "p-bo-sen-3", "title": "Rural Electrification & Transformer Installations in Biu", "category": "Infrastructure", "description": "Supplying 20 high-voltage transformers across rural farming communities.", "status": "fulfilled", "date_made": "2024-01-15", "budget_allocated": "₦450 Million", "progress_pct": 100, "milestones": ["Transformers Energized in Biu and Hawul"]}]}
    ]
}

print("Senators dataset prepared.")
